export const SCENE_IMAGES: Record<number, string> = {
  11: "/images/prod/ours-blanc.png",
  12: "/images/prod/velo.png",
  20: "/images/prod/bougeoir-or.png",
  21: "/images/prod/lanterne-argent.png",
  22: "/images/prod/lanterne-noir.png",
  23: "/images/prod/lanterne-blanche.png",
  24: "/images/prod/lustre-12-branches.png",
  25: "/images/prod/prisme.png",
  26: "/images/prod/bride-to-be-led.png",
  27: "/images/prod/bougeoire-etincelle.png",
  29: "/images/prod/coffret-verre-laiton.png",
  32: "/images/prod/pack-candy-bar-verre.png",
  34: "/images/prod/photophore-transparent.png",
  36: "/images/prod/fontaine-agrume.png",
  46: "/images/prod/feuille-or.png",
  48: "/images/prod/presentoir-gateau-2.png",
  49: "/images/prod/urne-cage.png",
  50: "/images/prod/bird-scoth.png",
  51: "/images/prod/pack-sou-verre.png",
  52: "/images/prod/porte-serviettes.png",
  53: "/images/prod/sous-assiettes-or.png",
  54: "/images/prod/sauciere.png",
  56: "/images/prod/serviette-emeraude.png",
  57: "/images/prod/chemin-table-rose.png",
  58: "/images/prod/nappe-papillon.png",
  60: "/images/prod/porte-carte-or.png",
  63: "/images/prod/panier-pain.png",
  64: "/images/prod/saliere-poivriere.png",
  65: "/images/prod/coussins-velour.png",
  66: "/images/prod/top-cake-diamand.png",
  70: "/images/prod/vase-oval.png",
  72: "/images/prod/vase-geometrique-blanc.png",
  74: "/images/prod/horloge.png",
  75: "/images/prod/sonnette-comptoir.png",
  76: "/images/prod/boa.png",
  78: "/images/prod/umbrella.png",
}

export const FEATURED_IDS = [1, 3, 5, 24, 61]

